FROM golang:1.11

LABEL maintainer="takemi.ohama@gmail.com"

RUN go get github.com/jinzhu/gorm github.com/jinzhu/gorm/dialects/mysql \
           github.com/joho/godotenv googlemaps.github.io/maps github.com/pkg/errors 
